import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";
import { Toaster } from "@/components/ui/sonner";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main
          className={`${inter.className} container max-md:py-0  min-h-screen`}
        >
          <ThemeProvider attribute="class" defaultTheme="system">
            <Toaster position="top-center" richColors />
            <Navbar />
            <div className="mt-40 mb-20">{children}</div>
            <Footer />
          </ThemeProvider>
        </main>
      </body>
    </html>
  );
}
