import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers/theme-provider";
import Navbar from "./Components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} container py-10 max-md:py-0 `}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
        >
          <Navbar/>
          <main>
              {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
